### PR TITLE
Update Continuous Integration

### PR DESCRIPTION
**Pull request by BasThomas**
- Updates Xcode to latest stable version (11.3.1)
- Updates Ruby to latest stable version (2.7.0)

### CODE REVIEW

**Comment by BasThomas** [comment]
> fatal: Could not read from remote repository.
>
>Please make sure you have the correct access rights
and the repository exists.

Hm, what gives? cc @JoeSSS

**Comment by jamuc** [comment]
Made you an admin @BasThomas

**Comment by jamuc** [comment]
I think

**Comment by BasThomas** [comment]
It works? 🤔

**Comment by BasThomas** [comment]
> Made you an admin @BasThomas

Already was 😛

**Comment by jamuc** [comment]
Oh well, I tried

**Pull request merged**
